# ------------------------
# FastAPI Deployment Object
# ------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-web-app-e-cloud-deployment
  labels:
    # 👈 Any KEY-VALUE pair is ACCEPTABLE here, convention is to use "app: fastapi-web-app-e-cloud-deployment"
    # But I am using "ramos-app-name" Key so that, I can show ANY CUSTOM KEY-VALUE pair can be Given
    ramos-app-name: fastapi-web-app-e-cloud-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      # "ramos-app-name: fastapi-e-cloud-pod" 👈 this KEY-VALUE Pair Must match the Below Pod's KEY-VALUE Pair
      ramos-app-name: fastapi-web-app-e-cloud-pod
  # This section defines the Pod template (metadata + spec)
  template:
    metadata:
      labels:
        ramos-app-name: fastapi-web-app-e-cloud-pod # 👈 this Must Match with "matchLabels" KEY-VALUE pair
    spec:
      # The initContainer runs a simple shell loop that waits until the TCP port on the Postgres service (postgres-service:5432) is open.
      initContainers:
          - name: wait-for-postgres
            image: busybox
            command: ['sh', '-c', 'until nc -z postgres-e-cloud-service 5432; do echo "waiting for postgres"; sleep 2; done;']
      containers:
        - name: e-cloud-learniverse-pod
          image: e-cloud-fastapi-docker-image
          imagePullPolicy: Never
          env:
            - name: DATABASE_USER
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "postgres"
            - name: DATABASE_HOST
              value: "postgres-e-cloud-service"   # 👈 Must be the Service name of "Postgres"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: "e_cloud_learniverse_db"
          ports:
            - containerPort: 9998